import { stateBet } from 'state-shared';

import { INITIAL_BOARD } from '../../game/constants';
import { assertJcaBookEvents } from '../../game/boardContract';
import type { BookEvent } from '../../game/typesBookEvent';
import type { Position, RawSymbol } from '../../game/types';
import { playBookEvents } from '../../game/utils';

/**
 * Visual Storybook fixtures for the approved JCA 6x6 symbol set.
 * These are NOT generated by the math engine and MUST NOT be passed to the RGS,
 * recorded as a real bet, or used to infer the game's paytable / RTP.
 * Old 6x5 books are intentionally not converted: doing so changes outcomes.
 */
export type JcaQaMode = 'base' | 'bonus';
export type JcaQaVariant = 'loss' | 'win' | 'cascade';
export type JcaQaEventName = BookEvent['type'];

const pos = (reel: number, row: number): Position => ({ reel, row });
const winningPositions: Position[] = [
    pos(0, 2), pos(0, 3), pos(0, 4),
    pos(1, 2), pos(1, 3), pos(1, 4),
    pos(2, 2), pos(2, 3), pos(2, 4),
];
const scatterPositions: Position[] = [pos(0, 5), pos(1, 4), pos(3, 4), pos(4, 6)];

const makeSymbol = (name: RawSymbol['name']): RawSymbol => {
    if (name === 'S') return { name: 'S', scatter: true };
    if (name === 'M') return { name: 'M', multiplier: 5 };
    return { name };
};

function makeBoard(options: { win: boolean; trigger: boolean }): RawSymbol[][] {
    // Exactly 6 reels × (1 hidden + 6 visible + 1 hidden) rows.
    const board = INITIAL_BOARD.map((reel) => reel.map((symbol) => ({ ...symbol })));
    // Avoid accidental scatter triggers during visual QA.
    for (const reel of board) {
        for (let row = 0; row < reel.length; row++) {
            if (reel[row].name === 'S') reel[row] = makeSymbol('L2');
        }
    }
    if (options.win) {
        for (const { reel, row } of winningPositions) board[reel][row] = makeSymbol('L1');
    }
    if (options.trigger) {
        for (const { reel, row } of scatterPositions) board[reel][row] = makeSymbol('S');
    }
    // Approved multiplier art is x5 only. Keep it outside the winning cluster.
    board[4][2] = makeSymbol('M');
    return board;
}

function reveal(board: RawSymbol[][], gameType: 'basegame' | 'freeSpins'): BookEvent {
    return {
        index: 0,
        type: 'reveal',
        board,
        gameType,
        paddingPositions: [0, 0, 0, 0, 0, 0],
        anticipation: [0, 0, 0, 0, 0, 0],
    };
}

function winInfo(): BookEvent {
    return {
        index: 0,
        type: 'winInfo',
        totalWin: 120,
        wins: [{
            symbol: 'L1',
            win: 120,
            positions: winningPositions.map(({ reel, row }) => pos(reel, row)),
            meta: {
                globalMult: 1,
                clusterMult: 1,
                winWithoutMult: 120,
                overlay: pos(1, 3),
            },
        }],
    };
}

function tumble(): BookEvent {
    return {
        index: 0,
        type: 'tumbleBoard',
        explodingSymbols: winningPositions.map(({ reel, row }) => pos(reel, row)),
        newSymbols: [
            [makeSymbol('L4'), makeSymbol('H5'), makeSymbol('L2')],
            [makeSymbol('H1'), makeSymbol('L3'), makeSymbol('H4')],
            [makeSymbol('L2'), makeSymbol('H3'), makeSymbol('L4')],
            [], [], [],
        ],
    };
}

function multiplierInfo(): BookEvent {
    return {
        index: 0,
        type: 'boardMultiplierInfo',
        multInfo: { positions: [{ reel: 4, row: 2, multiplier: 5 }] },
        winInfo: { tumbleWin: 120, boardMult: 5, totalWin: 600 },
    };
}

function winFlow(cascade: boolean): BookEvent[] {
    const events: BookEvent[] = [
        winInfo(),
        { index: 0, type: 'updateTumbleWin', amount: 120 },
    ];
    if (cascade) {
        events.push(tumble(), multiplierInfo(), { index: 0, type: 'updateGlobalMult', globalMult: 2 });
    }
    return events;
}

function finish(amount: number): BookEvent[] {
    return [
        { index: 0, type: 'setWin', amount, winLevel: 2 },
        { index: 0, type: 'setTotalWin', amount },
        { index: 0, type: 'finalWin', amount },
    ];
}

function withIndices(events: BookEvent[]): BookEvent[] {
    return events.map((event, index) => ({ ...event, index } as BookEvent));
}

/** Full, self-contained 6x6 event stream for MODE_BASE or MODE_BONUS Storybook. */
export function getJcaModeQaBook(
    mode: JcaQaMode,
    variant: JcaQaVariant = 'cascade',
): BookEvent[] {
    const isWin = variant !== 'loss';
    const hasCascade = variant === 'cascade';
    if (mode === 'base') {
        const events: BookEvent[] = [reveal(makeBoard({ win: isWin, trigger: false }), 'basegame')];
        if (isWin) events.push(...winFlow(hasCascade));
        events.push(...(isWin ? finish(hasCascade ? 600 : 120) : [
            { index: 0, type: 'setTotalWin', amount: 0 } as BookEvent,
            { index: 0, type: 'finalWin', amount: 0 } as BookEvent,
        ]));
        const book = withIndices(events);
        assertJcaBookEvents(book);
        return book;
    }

    const events: BookEvent[] = [
        // Bonus purchase demonstration: four S symbols first appear on a BASE reel.
        reveal(makeBoard({ win: false, trigger: true }), 'basegame'),
        { index: 0, type: 'freeSpinTrigger', totalFs: 2, positions: scatterPositions },
        { index: 0, type: 'updateFreeSpin', amount: 1, total: 2 },
        reveal(makeBoard({ win: isWin, trigger: false }), 'freeSpins'),
    ];
    if (isWin) events.push(...winFlow(hasCascade));
    events.push(
        { index: 0, type: 'updateFreeSpin', amount: 2, total: 2 },
        reveal(makeBoard({ win: false, trigger: false }), 'freeSpins'),
    );
    const amount = isWin ? (hasCascade ? 600 : 120) : 0;
    events.push(
        { index: 0, type: 'setTotalWin', amount },
        { index: 0, type: 'freeSpinEnd', amount, winLevel: amount ? 2 : 1 },
        { index: 0, type: 'finalWin', amount },
    );
    const book = withIndices(events);
    assertJcaBookEvents(book);
    return book;
}

/** Replays the real visual event handler, but never submits a wager. */
export async function playJcaModeQaBook(
    mode: JcaQaMode,
    variant: JcaQaVariant = 'cascade',
): Promise<void> {
    const book = getJcaModeQaBook(mode, variant);
    stateBet.winBookEventAmount = 0;
    await playBookEvents(book);
}

/**
 * For an isolated Storybook event, replay the prerequisite reveal/trigger/win
 * sequence from a fresh board. Playing a tumble or win without its board is invalid.
 */
export async function playJcaModeQaThroughEvent(
    mode: JcaQaMode,
    type: JcaQaEventName,
): Promise<void> {
    // The bonus-trigger sequence originates in basegame by design.
    const source = mode === 'base' && ['freeSpinTrigger', 'updateFreeSpin', 'freeSpinEnd'].includes(type)
        ? 'bonus' : mode;
    const book = getJcaModeQaBook(source, 'cascade');
    const index = type === 'reveal' && mode === 'bonus'
        ? book.findIndex((event) => event.type === 'reveal' && event.gameType === 'freeSpins')
        : book.findIndex((event) => event.type === type);
    if (index < 0) {
        throw new Error(`JCA QA ${source}: no authored ${type} event; legacy 6x5 data cannot be replayed.`);
    }
    const prefix = book.slice(0, index + 1);
    assertJcaBookEvents(prefix);
    stateBet.winBookEventAmount = 0;
    await playBookEvents(prefix);
}
